// Code generated by protoc-gen-go.
// source: bc.proto
// DO NOT EDIT!

/*
Package bc is a generated protocol buffer package.

It is generated from these files:
	bc.proto

It has these top-level messages:
	Hash
	Program
	AssetID
	AssetAmount
	AssetDefinition
	ValueSource
	ValueDestination
	BlockHeader
	TxHeader
	Mux
	Nonce
	Output
	Retirement
	TimeRange
	Issuance
	Spend
	ProtoTx
	ProtoBlock
*/
package bc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hash struct {
	V0 uint64 `protobuf:"fixed64,1,opt,name=v0" json:"v0,omitempty"`
	V1 uint64 `protobuf:"fixed64,2,opt,name=v1" json:"v1,omitempty"`
	V2 uint64 `protobuf:"fixed64,3,opt,name=v2" json:"v2,omitempty"`
	V3 uint64 `protobuf:"fixed64,4,opt,name=v3" json:"v3,omitempty"`
}

func (m *Hash) Reset()                    { *m = Hash{} }
func (m *Hash) String() string            { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()               {}
func (*Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hash) GetV0() uint64 {
	if m != nil {
		return m.V0
	}
	return 0
}

func (m *Hash) GetV1() uint64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *Hash) GetV2() uint64 {
	if m != nil {
		return m.V2
	}
	return 0
}

func (m *Hash) GetV3() uint64 {
	if m != nil {
		return m.V3
	}
	return 0
}

type Program struct {
	VmVersion uint64 `protobuf:"varint,1,opt,name=vm_version,json=vmVersion" json:"vm_version,omitempty"`
	Code      []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *Program) Reset()                    { *m = Program{} }
func (m *Program) String() string            { return proto.CompactTextString(m) }
func (*Program) ProtoMessage()               {}
func (*Program) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Program) GetVmVersion() uint64 {
	if m != nil {
		return m.VmVersion
	}
	return 0
}

func (m *Program) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

// This message type duplicates Hash, above. One alternative is to
// embed a Hash inside an AssetID. But it's useful for AssetID to be
// plain old data (without pointers). Another alternative is use Hash
// in any protobuf types where an AssetID is called for, but it's
// preferable to have type safety.
type AssetID struct {
	V0 uint64 `protobuf:"fixed64,1,opt,name=v0" json:"v0,omitempty"`
	V1 uint64 `protobuf:"fixed64,2,opt,name=v1" json:"v1,omitempty"`
	V2 uint64 `protobuf:"fixed64,3,opt,name=v2" json:"v2,omitempty"`
	V3 uint64 `protobuf:"fixed64,4,opt,name=v3" json:"v3,omitempty"`
}

func (m *AssetID) Reset()                    { *m = AssetID{} }
func (m *AssetID) String() string            { return proto.CompactTextString(m) }
func (*AssetID) ProtoMessage()               {}
func (*AssetID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AssetID) GetV0() uint64 {
	if m != nil {
		return m.V0
	}
	return 0
}

func (m *AssetID) GetV1() uint64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *AssetID) GetV2() uint64 {
	if m != nil {
		return m.V2
	}
	return 0
}

func (m *AssetID) GetV3() uint64 {
	if m != nil {
		return m.V3
	}
	return 0
}

type AssetAmount struct {
	AssetId *AssetID `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	Amount  uint64   `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *AssetAmount) Reset()                    { *m = AssetAmount{} }
func (m *AssetAmount) String() string            { return proto.CompactTextString(m) }
func (*AssetAmount) ProtoMessage()               {}
func (*AssetAmount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AssetAmount) GetAssetId() *AssetID {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *AssetAmount) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type AssetDefinition struct {
	InitialBlockId  *Hash    `protobuf:"bytes,1,opt,name=initial_block_id,json=initialBlockId" json:"initial_block_id,omitempty"`
	IssuanceProgram *Program `protobuf:"bytes,2,opt,name=issuance_program,json=issuanceProgram" json:"issuance_program,omitempty"`
	Data            *Hash    `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *AssetDefinition) Reset()                    { *m = AssetDefinition{} }
func (m *AssetDefinition) String() string            { return proto.CompactTextString(m) }
func (*AssetDefinition) ProtoMessage()               {}
func (*AssetDefinition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AssetDefinition) GetInitialBlockId() *Hash {
	if m != nil {
		return m.InitialBlockId
	}
	return nil
}

func (m *AssetDefinition) GetIssuanceProgram() *Program {
	if m != nil {
		return m.IssuanceProgram
	}
	return nil
}

func (m *AssetDefinition) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValueSource struct {
	Ref      *Hash        `protobuf:"bytes,1,opt,name=ref" json:"ref,omitempty"`
	Value    *AssetAmount `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Position uint64       `protobuf:"varint,3,opt,name=position" json:"position,omitempty"`
}

func (m *ValueSource) Reset()                    { *m = ValueSource{} }
func (m *ValueSource) String() string            { return proto.CompactTextString(m) }
func (*ValueSource) ProtoMessage()               {}
func (*ValueSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ValueSource) GetRef() *Hash {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *ValueSource) GetValue() *AssetAmount {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueSource) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type ValueDestination struct {
	Ref      *Hash        `protobuf:"bytes,1,opt,name=ref" json:"ref,omitempty"`
	Value    *AssetAmount `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Position uint64       `protobuf:"varint,3,opt,name=position" json:"position,omitempty"`
}

func (m *ValueDestination) Reset()                    { *m = ValueDestination{} }
func (m *ValueDestination) String() string            { return proto.CompactTextString(m) }
func (*ValueDestination) ProtoMessage()               {}
func (*ValueDestination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ValueDestination) GetRef() *Hash {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *ValueDestination) GetValue() *AssetAmount {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueDestination) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type BlockHeader struct {
	Body    *BlockHeader_Body    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Witness *BlockHeader_Witness `protobuf:"bytes,2,opt,name=witness" json:"witness,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BlockHeader) GetBody() *BlockHeader_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *BlockHeader) GetWitness() *BlockHeader_Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

type BlockHeader_Body struct {
	Version              uint64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Height               uint64 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	PreviousBlockId      *Hash  `protobuf:"bytes,3,opt,name=previous_block_id,json=previousBlockId" json:"previous_block_id,omitempty"`
	TimestampMs          uint64 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs" json:"timestamp_ms,omitempty"`
	TransactionsRoot     *Hash  `protobuf:"bytes,5,opt,name=transactions_root,json=transactionsRoot" json:"transactions_root,omitempty"`
	AssetsRoot           *Hash  `protobuf:"bytes,6,opt,name=assets_root,json=assetsRoot" json:"assets_root,omitempty"`
	NextConsensusProgram []byte `protobuf:"bytes,7,opt,name=next_consensus_program,json=nextConsensusProgram,proto3" json:"next_consensus_program,omitempty"`
	ExtHash              *Hash  `protobuf:"bytes,8,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *BlockHeader_Body) Reset()                    { *m = BlockHeader_Body{} }
func (m *BlockHeader_Body) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader_Body) ProtoMessage()               {}
func (*BlockHeader_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *BlockHeader_Body) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader_Body) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader_Body) GetPreviousBlockId() *Hash {
	if m != nil {
		return m.PreviousBlockId
	}
	return nil
}

func (m *BlockHeader_Body) GetTimestampMs() uint64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

func (m *BlockHeader_Body) GetTransactionsRoot() *Hash {
	if m != nil {
		return m.TransactionsRoot
	}
	return nil
}

func (m *BlockHeader_Body) GetAssetsRoot() *Hash {
	if m != nil {
		return m.AssetsRoot
	}
	return nil
}

func (m *BlockHeader_Body) GetNextConsensusProgram() []byte {
	if m != nil {
		return m.NextConsensusProgram
	}
	return nil
}

func (m *BlockHeader_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type BlockHeader_Witness struct {
	Arguments [][]byte `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (m *BlockHeader_Witness) Reset()                    { *m = BlockHeader_Witness{} }
func (m *BlockHeader_Witness) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader_Witness) ProtoMessage()               {}
func (*BlockHeader_Witness) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

func (m *BlockHeader_Witness) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type TxHeader struct {
	Body *TxHeader_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *TxHeader) Reset()                    { *m = TxHeader{} }
func (m *TxHeader) String() string            { return proto.CompactTextString(m) }
func (*TxHeader) ProtoMessage()               {}
func (*TxHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TxHeader) GetBody() *TxHeader_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type TxHeader_Body struct {
	Version   uint64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	ResultIds []*Hash `protobuf:"bytes,2,rep,name=result_ids,json=resultIds" json:"result_ids,omitempty"`
	Data      *Hash   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	MinTimeMs uint64  `protobuf:"varint,4,opt,name=min_time_ms,json=minTimeMs" json:"min_time_ms,omitempty"`
	MaxTimeMs uint64  `protobuf:"varint,5,opt,name=max_time_ms,json=maxTimeMs" json:"max_time_ms,omitempty"`
	ExtHash   *Hash   `protobuf:"bytes,6,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *TxHeader_Body) Reset()                    { *m = TxHeader_Body{} }
func (m *TxHeader_Body) String() string            { return proto.CompactTextString(m) }
func (*TxHeader_Body) ProtoMessage()               {}
func (*TxHeader_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *TxHeader_Body) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TxHeader_Body) GetResultIds() []*Hash {
	if m != nil {
		return m.ResultIds
	}
	return nil
}

func (m *TxHeader_Body) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TxHeader_Body) GetMinTimeMs() uint64 {
	if m != nil {
		return m.MinTimeMs
	}
	return 0
}

func (m *TxHeader_Body) GetMaxTimeMs() uint64 {
	if m != nil {
		return m.MaxTimeMs
	}
	return 0
}

func (m *TxHeader_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Mux struct {
	Body    *Mux_Body    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Witness *Mux_Witness `protobuf:"bytes,2,opt,name=witness" json:"witness,omitempty"`
}

func (m *Mux) Reset()                    { *m = Mux{} }
func (m *Mux) String() string            { return proto.CompactTextString(m) }
func (*Mux) ProtoMessage()               {}
func (*Mux) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Mux) GetBody() *Mux_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Mux) GetWitness() *Mux_Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

type Mux_Body struct {
	Sources []*ValueSource `protobuf:"bytes,1,rep,name=sources" json:"sources,omitempty"`
	Program *Program       `protobuf:"bytes,2,opt,name=program" json:"program,omitempty"`
	ExtHash *Hash          `protobuf:"bytes,3,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Mux_Body) Reset()                    { *m = Mux_Body{} }
func (m *Mux_Body) String() string            { return proto.CompactTextString(m) }
func (*Mux_Body) ProtoMessage()               {}
func (*Mux_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *Mux_Body) GetSources() []*ValueSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Mux_Body) GetProgram() *Program {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *Mux_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Mux_Witness struct {
	Destinations []*ValueDestination `protobuf:"bytes,1,rep,name=destinations" json:"destinations,omitempty"`
	Arguments    [][]byte            `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (m *Mux_Witness) Reset()                    { *m = Mux_Witness{} }
func (m *Mux_Witness) String() string            { return proto.CompactTextString(m) }
func (*Mux_Witness) ProtoMessage()               {}
func (*Mux_Witness) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 1} }

func (m *Mux_Witness) GetDestinations() []*ValueDestination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *Mux_Witness) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Nonce struct {
	Body    *Nonce_Body    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Witness *Nonce_Witness `protobuf:"bytes,2,opt,name=witness" json:"witness,omitempty"`
}

func (m *Nonce) Reset()                    { *m = Nonce{} }
func (m *Nonce) String() string            { return proto.CompactTextString(m) }
func (*Nonce) ProtoMessage()               {}
func (*Nonce) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Nonce) GetBody() *Nonce_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Nonce) GetWitness() *Nonce_Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

type Nonce_Body struct {
	Program     *Program `protobuf:"bytes,1,opt,name=program" json:"program,omitempty"`
	TimeRangeId *Hash    `protobuf:"bytes,2,opt,name=time_range_id,json=timeRangeId" json:"time_range_id,omitempty"`
	ExtHash     *Hash    `protobuf:"bytes,3,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Nonce_Body) Reset()                    { *m = Nonce_Body{} }
func (m *Nonce_Body) String() string            { return proto.CompactTextString(m) }
func (*Nonce_Body) ProtoMessage()               {}
func (*Nonce_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *Nonce_Body) GetProgram() *Program {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *Nonce_Body) GetTimeRangeId() *Hash {
	if m != nil {
		return m.TimeRangeId
	}
	return nil
}

func (m *Nonce_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Nonce_Witness struct {
	Arguments  [][]byte `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	AnchoredId *Hash    `protobuf:"bytes,2,opt,name=anchored_id,json=anchoredId" json:"anchored_id,omitempty"`
}

func (m *Nonce_Witness) Reset()                    { *m = Nonce_Witness{} }
func (m *Nonce_Witness) String() string            { return proto.CompactTextString(m) }
func (*Nonce_Witness) ProtoMessage()               {}
func (*Nonce_Witness) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 1} }

func (m *Nonce_Witness) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Nonce_Witness) GetAnchoredId() *Hash {
	if m != nil {
		return m.AnchoredId
	}
	return nil
}

type Output struct {
	Body    *Output_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Ordinal uint64       `protobuf:"varint,2,opt,name=ordinal" json:"ordinal,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Output) GetBody() *Output_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Output) GetOrdinal() uint64 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

type Output_Body struct {
	Source         *ValueSource `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	ControlProgram *Program     `protobuf:"bytes,2,opt,name=control_program,json=controlProgram" json:"control_program,omitempty"`
	Data           *Hash        `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	ExtHash        *Hash        `protobuf:"bytes,4,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Output_Body) Reset()                    { *m = Output_Body{} }
func (m *Output_Body) String() string            { return proto.CompactTextString(m) }
func (*Output_Body) ProtoMessage()               {}
func (*Output_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *Output_Body) GetSource() *ValueSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Output_Body) GetControlProgram() *Program {
	if m != nil {
		return m.ControlProgram
	}
	return nil
}

func (m *Output_Body) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Output_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Retirement struct {
	Body    *Retirement_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Ordinal uint64           `protobuf:"varint,2,opt,name=ordinal" json:"ordinal,omitempty"`
}

func (m *Retirement) Reset()                    { *m = Retirement{} }
func (m *Retirement) String() string            { return proto.CompactTextString(m) }
func (*Retirement) ProtoMessage()               {}
func (*Retirement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Retirement) GetBody() *Retirement_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Retirement) GetOrdinal() uint64 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

type Retirement_Body struct {
	Source  *ValueSource `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Data    *Hash        `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	ExtHash *Hash        `protobuf:"bytes,3,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Retirement_Body) Reset()                    { *m = Retirement_Body{} }
func (m *Retirement_Body) String() string            { return proto.CompactTextString(m) }
func (*Retirement_Body) ProtoMessage()               {}
func (*Retirement_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

func (m *Retirement_Body) GetSource() *ValueSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Retirement_Body) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Retirement_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type TimeRange struct {
	Body *TimeRange_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TimeRange) GetBody() *TimeRange_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type TimeRange_Body struct {
	MinTimeMs uint64 `protobuf:"varint,1,opt,name=min_time_ms,json=minTimeMs" json:"min_time_ms,omitempty"`
	MaxTimeMs uint64 `protobuf:"varint,2,opt,name=max_time_ms,json=maxTimeMs" json:"max_time_ms,omitempty"`
	ExtHash   *Hash  `protobuf:"bytes,3,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *TimeRange_Body) Reset()                    { *m = TimeRange_Body{} }
func (m *TimeRange_Body) String() string            { return proto.CompactTextString(m) }
func (*TimeRange_Body) ProtoMessage()               {}
func (*TimeRange_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

func (m *TimeRange_Body) GetMinTimeMs() uint64 {
	if m != nil {
		return m.MinTimeMs
	}
	return 0
}

func (m *TimeRange_Body) GetMaxTimeMs() uint64 {
	if m != nil {
		return m.MaxTimeMs
	}
	return 0
}

func (m *TimeRange_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Issuance struct {
	Body    *Issuance_Body    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Witness *Issuance_Witness `protobuf:"bytes,2,opt,name=witness" json:"witness,omitempty"`
	Ordinal uint64            `protobuf:"varint,3,opt,name=ordinal" json:"ordinal,omitempty"`
}

func (m *Issuance) Reset()                    { *m = Issuance{} }
func (m *Issuance) String() string            { return proto.CompactTextString(m) }
func (*Issuance) ProtoMessage()               {}
func (*Issuance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Issuance) GetBody() *Issuance_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Issuance) GetWitness() *Issuance_Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *Issuance) GetOrdinal() uint64 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

type Issuance_Body struct {
	AnchorId *Hash        `protobuf:"bytes,1,opt,name=anchor_id,json=anchorId" json:"anchor_id,omitempty"`
	Value    *AssetAmount `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Data     *Hash        `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	ExtHash  *Hash        `protobuf:"bytes,4,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Issuance_Body) Reset()                    { *m = Issuance_Body{} }
func (m *Issuance_Body) String() string            { return proto.CompactTextString(m) }
func (*Issuance_Body) ProtoMessage()               {}
func (*Issuance_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14, 0} }

func (m *Issuance_Body) GetAnchorId() *Hash {
	if m != nil {
		return m.AnchorId
	}
	return nil
}

func (m *Issuance_Body) GetValue() *AssetAmount {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Issuance_Body) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Issuance_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Issuance_Witness struct {
	Destination     *ValueDestination `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	AssetDefinition *AssetDefinition  `protobuf:"bytes,2,opt,name=asset_definition,json=assetDefinition" json:"asset_definition,omitempty"`
	Arguments       [][]byte          `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	AnchoredId      *Hash             `protobuf:"bytes,4,opt,name=anchored_id,json=anchoredId" json:"anchored_id,omitempty"`
}

func (m *Issuance_Witness) Reset()                    { *m = Issuance_Witness{} }
func (m *Issuance_Witness) String() string            { return proto.CompactTextString(m) }
func (*Issuance_Witness) ProtoMessage()               {}
func (*Issuance_Witness) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14, 1} }

func (m *Issuance_Witness) GetDestination() *ValueDestination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Issuance_Witness) GetAssetDefinition() *AssetDefinition {
	if m != nil {
		return m.AssetDefinition
	}
	return nil
}

func (m *Issuance_Witness) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Issuance_Witness) GetAnchoredId() *Hash {
	if m != nil {
		return m.AnchoredId
	}
	return nil
}

type Spend struct {
	Body    *Spend_Body    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Witness *Spend_Witness `protobuf:"bytes,2,opt,name=witness" json:"witness,omitempty"`
	Ordinal uint64         `protobuf:"varint,3,opt,name=ordinal" json:"ordinal,omitempty"`
}

func (m *Spend) Reset()                    { *m = Spend{} }
func (m *Spend) String() string            { return proto.CompactTextString(m) }
func (*Spend) ProtoMessage()               {}
func (*Spend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Spend) GetBody() *Spend_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Spend) GetWitness() *Spend_Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *Spend) GetOrdinal() uint64 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

type Spend_Body struct {
	SpentOutputId *Hash `protobuf:"bytes,1,opt,name=spent_output_id,json=spentOutputId" json:"spent_output_id,omitempty"`
	Data          *Hash `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	ExtHash       *Hash `protobuf:"bytes,3,opt,name=ext_hash,json=extHash" json:"ext_hash,omitempty"`
}

func (m *Spend_Body) Reset()                    { *m = Spend_Body{} }
func (m *Spend_Body) String() string            { return proto.CompactTextString(m) }
func (*Spend_Body) ProtoMessage()               {}
func (*Spend_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

func (m *Spend_Body) GetSpentOutputId() *Hash {
	if m != nil {
		return m.SpentOutputId
	}
	return nil
}

func (m *Spend_Body) GetData() *Hash {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Spend_Body) GetExtHash() *Hash {
	if m != nil {
		return m.ExtHash
	}
	return nil
}

type Spend_Witness struct {
	Destination *ValueDestination `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Arguments   [][]byte          `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	AnchoredId  *Hash             `protobuf:"bytes,3,opt,name=anchored_id,json=anchoredId" json:"anchored_id,omitempty"`
}

func (m *Spend_Witness) Reset()                    { *m = Spend_Witness{} }
func (m *Spend_Witness) String() string            { return proto.CompactTextString(m) }
func (*Spend_Witness) ProtoMessage()               {}
func (*Spend_Witness) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 1} }

func (m *Spend_Witness) GetDestination() *ValueDestination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Spend_Witness) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Spend_Witness) GetAnchoredId() *Hash {
	if m != nil {
		return m.AnchoredId
	}
	return nil
}

type ProtoTx struct {
	Header      *TxHeader     `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Muxes       []*Mux        `protobuf:"bytes,2,rep,name=muxes" json:"muxes,omitempty"`
	Nonces      []*Nonce      `protobuf:"bytes,3,rep,name=nonces" json:"nonces,omitempty"`
	Outputs     []*Output     `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	Retirements []*Retirement `protobuf:"bytes,5,rep,name=retirements" json:"retirements,omitempty"`
	Timeranges  []*TimeRange  `protobuf:"bytes,6,rep,name=timeranges" json:"timeranges,omitempty"`
	Issuances   []*Issuance   `protobuf:"bytes,7,rep,name=issuances" json:"issuances,omitempty"`
	Spends      []*Spend      `protobuf:"bytes,8,rep,name=spends" json:"spends,omitempty"`
}

func (m *ProtoTx) Reset()                    { *m = ProtoTx{} }
func (m *ProtoTx) String() string            { return proto.CompactTextString(m) }
func (*ProtoTx) ProtoMessage()               {}
func (*ProtoTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ProtoTx) GetHeader() *TxHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProtoTx) GetMuxes() []*Mux {
	if m != nil {
		return m.Muxes
	}
	return nil
}

func (m *ProtoTx) GetNonces() []*Nonce {
	if m != nil {
		return m.Nonces
	}
	return nil
}

func (m *ProtoTx) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *ProtoTx) GetRetirements() []*Retirement {
	if m != nil {
		return m.Retirements
	}
	return nil
}

func (m *ProtoTx) GetTimeranges() []*TimeRange {
	if m != nil {
		return m.Timeranges
	}
	return nil
}

func (m *ProtoTx) GetIssuances() []*Issuance {
	if m != nil {
		return m.Issuances
	}
	return nil
}

func (m *ProtoTx) GetSpends() []*Spend {
	if m != nil {
		return m.Spends
	}
	return nil
}

type ProtoBlock struct {
	Header       *BlockHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*ProtoTx   `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *ProtoBlock) Reset()                    { *m = ProtoBlock{} }
func (m *ProtoBlock) String() string            { return proto.CompactTextString(m) }
func (*ProtoBlock) ProtoMessage()               {}
func (*ProtoBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ProtoBlock) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProtoBlock) GetTransactions() []*ProtoTx {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Hash)(nil), "bc.Hash")
	proto.RegisterType((*Program)(nil), "bc.Program")
	proto.RegisterType((*AssetID)(nil), "bc.AssetID")
	proto.RegisterType((*AssetAmount)(nil), "bc.AssetAmount")
	proto.RegisterType((*AssetDefinition)(nil), "bc.AssetDefinition")
	proto.RegisterType((*ValueSource)(nil), "bc.ValueSource")
	proto.RegisterType((*ValueDestination)(nil), "bc.ValueDestination")
	proto.RegisterType((*BlockHeader)(nil), "bc.BlockHeader")
	proto.RegisterType((*BlockHeader_Body)(nil), "bc.BlockHeader.Body")
	proto.RegisterType((*BlockHeader_Witness)(nil), "bc.BlockHeader.Witness")
	proto.RegisterType((*TxHeader)(nil), "bc.TxHeader")
	proto.RegisterType((*TxHeader_Body)(nil), "bc.TxHeader.Body")
	proto.RegisterType((*Mux)(nil), "bc.Mux")
	proto.RegisterType((*Mux_Body)(nil), "bc.Mux.Body")
	proto.RegisterType((*Mux_Witness)(nil), "bc.Mux.Witness")
	proto.RegisterType((*Nonce)(nil), "bc.Nonce")
	proto.RegisterType((*Nonce_Body)(nil), "bc.Nonce.Body")
	proto.RegisterType((*Nonce_Witness)(nil), "bc.Nonce.Witness")
	proto.RegisterType((*Output)(nil), "bc.Output")
	proto.RegisterType((*Output_Body)(nil), "bc.Output.Body")
	proto.RegisterType((*Retirement)(nil), "bc.Retirement")
	proto.RegisterType((*Retirement_Body)(nil), "bc.Retirement.Body")
	proto.RegisterType((*TimeRange)(nil), "bc.TimeRange")
	proto.RegisterType((*TimeRange_Body)(nil), "bc.TimeRange.Body")
	proto.RegisterType((*Issuance)(nil), "bc.Issuance")
	proto.RegisterType((*Issuance_Body)(nil), "bc.Issuance.Body")
	proto.RegisterType((*Issuance_Witness)(nil), "bc.Issuance.Witness")
	proto.RegisterType((*Spend)(nil), "bc.Spend")
	proto.RegisterType((*Spend_Body)(nil), "bc.Spend.Body")
	proto.RegisterType((*Spend_Witness)(nil), "bc.Spend.Witness")
	proto.RegisterType((*ProtoTx)(nil), "bc.ProtoTx")
	proto.RegisterType((*ProtoBlock)(nil), "bc.ProtoBlock")
}

func init() { proto.RegisterFile("bc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x85, 0x48, 0x4a, 0x94, 0xae, 0x14, 0xcb, 0x9e, 0x18, 0xf9, 0x08, 0x21, 0xf9, 0x90, 0x30,
	0x3f, 0xb6, 0xfb, 0xe3, 0xfa, 0xaf, 0x41, 0x17, 0x45, 0x81, 0xa4, 0x46, 0x11, 0x2d, 0xdc, 0x16,
	0x13, 0x23, 0x5d, 0x0a, 0x14, 0x39, 0xb6, 0x88, 0x88, 0x1c, 0x95, 0x43, 0xaa, 0x0a, 0x8a, 0x02,
	0x59, 0xf7, 0x05, 0xba, 0xe8, 0xa6, 0xcb, 0xee, 0xba, 0xe9, 0x1b, 0x74, 0x51, 0xa0, 0x28, 0xfa,
	0x10, 0x45, 0x9f, 0xa0, 0xeb, 0x2e, 0x8a, 0x19, 0xce, 0x90, 0x43, 0xda, 0x96, 0x1d, 0x24, 0xdd,
	0x71, 0x78, 0x2e, 0xef, 0xcc, 0x9c, 0x7b, 0xe6, 0xcc, 0x25, 0xb4, 0xc7, 0xfe, 0xf6, 0x2c, 0xa1,
	0x29, 0x45, 0xc6, 0xd8, 0x77, 0x3f, 0x01, 0xeb, 0x89, 0xc7, 0x26, 0x68, 0x05, 0x8c, 0xf9, 0x8e,
	0xd3, 0xb8, 0xdd, 0xd8, 0x6c, 0x61, 0x63, 0xbe, 0x23, 0xc6, 0xbb, 0x8e, 0x21, 0xc7, 0xbb, 0x62,
	0xbc, 0xe7, 0x98, 0x72, 0xbc, 0x27, 0xc6, 0xfb, 0x8e, 0x25, 0xc7, 0xfb, 0xee, 0x87, 0x60, 0x7f,
	0x9e, 0xd0, 0xd3, 0xc4, 0x8b, 0xd0, 0x2d, 0x80, 0x79, 0x34, 0x9a, 0x93, 0x84, 0x85, 0x34, 0x16,
	0x29, 0x2d, 0xdc, 0x99, 0x47, 0xcf, 0xf2, 0x17, 0x08, 0x81, 0xe5, 0xd3, 0x80, 0x88, 0xdc, 0x3d,
	0x2c, 0x9e, 0xdd, 0x21, 0xd8, 0x8f, 0x18, 0x23, 0xe9, 0xf0, 0xf0, 0xb5, 0x17, 0x72, 0x04, 0x5d,
	0x91, 0xea, 0x51, 0x44, 0xb3, 0x38, 0x45, 0x0f, 0xa0, 0xed, 0xf1, 0xe1, 0x28, 0x0c, 0x44, 0xd2,
	0xee, 0x5e, 0x77, 0x7b, 0xec, 0x6f, 0xcb, 0xd9, 0xb0, 0x2d, 0xc0, 0x61, 0x80, 0x6e, 0x40, 0xcb,
	0x13, 0x5f, 0x88, 0xa9, 0x2c, 0x2c, 0x47, 0xee, 0xf7, 0x0d, 0xe8, 0x8b, 0xe0, 0x43, 0x72, 0x12,
	0xc6, 0x61, 0xca, 0x77, 0xb0, 0x07, 0xab, 0xe2, 0xd1, 0x9b, 0x8e, 0xc6, 0x53, 0xea, 0x3f, 0x2f,
	0x73, 0xb7, 0x79, 0x6e, 0xce, 0x27, 0x5e, 0x91, 0x11, 0x8f, 0x79, 0xc0, 0x30, 0x40, 0x0f, 0x61,
	0x35, 0x64, 0x2c, 0xf3, 0x62, 0x9f, 0x8c, 0x66, 0x39, 0x51, 0x62, 0x26, 0xb9, 0x1e, 0xc9, 0x1d,
	0xee, 0xab, 0x20, 0x45, 0xe6, 0x4d, 0xb0, 0x02, 0x2f, 0xf5, 0xc4, 0x86, 0xf5, 0xfc, 0xe2, 0xad,
	0x3b, 0x85, 0xee, 0x33, 0x6f, 0x9a, 0x91, 0xa7, 0x34, 0x4b, 0x7c, 0x82, 0x06, 0x60, 0x26, 0xe4,
	0xe4, 0xcc, 0x5a, 0xf8, 0x4b, 0x74, 0x1f, 0x9a, 0x73, 0x1e, 0x2a, 0x67, 0xed, 0x17, 0x2c, 0xe4,
	0x44, 0xe1, 0x1c, 0x45, 0x03, 0x68, 0xcf, 0x28, 0x13, 0xfb, 0x14, 0x73, 0x5a, 0xb8, 0x18, 0xbb,
	0x5f, 0xc2, 0xaa, 0x98, 0xed, 0x90, 0xb0, 0x34, 0x8c, 0x3d, 0xc1, 0xc5, 0x7f, 0x3c, 0xe5, 0x5f,
	0x26, 0x74, 0x05, 0x85, 0x4f, 0x88, 0x17, 0x90, 0x04, 0x6d, 0x82, 0x35, 0xa6, 0xc1, 0x0b, 0x39,
	0xdf, 0x3a, 0xcf, 0xa8, 0xc1, 0xdb, 0x8f, 0x69, 0xf0, 0x02, 0x8b, 0x08, 0xb4, 0x0b, 0xf6, 0x57,
	0x61, 0x1a, 0x13, 0xc6, 0xe4, 0xf4, 0xff, 0xab, 0x07, 0x7f, 0x91, 0xc3, 0x58, 0xc5, 0x0d, 0xfe,
	0x30, 0xc0, 0xe2, 0x19, 0x90, 0x03, 0x76, 0x55, 0xbe, 0x6a, 0xc8, 0x65, 0x32, 0x21, 0xe1, 0xe9,
	0xa4, 0x90, 0x49, 0x3e, 0x42, 0x07, 0xb0, 0x36, 0x4b, 0xc8, 0x3c, 0xa4, 0x19, 0x2b, 0x35, 0x51,
	0xaf, 0x59, 0x5f, 0x85, 0x28, 0x51, 0xdc, 0x81, 0x5e, 0x1a, 0x46, 0x84, 0xa5, 0x5e, 0x34, 0x1b,
	0x45, 0x4c, 0xa8, 0xd8, 0xc2, 0xdd, 0xe2, 0xdd, 0x11, 0x43, 0xef, 0xc3, 0x5a, 0x9a, 0x78, 0x31,
	0xf3, 0x7c, 0xce, 0x07, 0x1b, 0x25, 0x94, 0xa6, 0x4e, 0xb3, 0x96, 0x78, 0x55, 0x0f, 0xc1, 0x94,
	0xa6, 0x68, 0x0b, 0xba, 0x42, 0xd9, 0xf2, 0x83, 0x56, 0xed, 0x03, 0xc8, 0x41, 0x11, 0x7a, 0x00,
	0x37, 0x62, 0xb2, 0x48, 0x47, 0x3e, 0x8d, 0x19, 0x89, 0x59, 0xc6, 0x0a, 0x7d, 0xda, 0xe2, 0x84,
	0xae, 0x73, 0xf4, 0x63, 0x05, 0x2a, 0x5d, 0xde, 0x85, 0x36, 0xff, 0x68, 0xe2, 0xb1, 0x89, 0xd3,
	0xae, 0x65, 0xb7, 0xc9, 0x22, 0xe5, 0x0f, 0x83, 0x0d, 0xb0, 0x25, 0xc9, 0xe8, 0x26, 0x74, 0xbc,
	0xe4, 0x34, 0x8b, 0x48, 0x9c, 0x32, 0xa7, 0x71, 0xdb, 0xdc, 0xec, 0xe1, 0xf2, 0x85, 0xfb, 0xd2,
	0x80, 0xf6, 0xf1, 0x42, 0xd6, 0xf8, 0x7e, 0xa5, 0xc6, 0x6b, 0x3c, 0xad, 0xc2, 0xb4, 0x02, 0x0f,
	0x7e, 0x6f, 0x5c, 0x5a, 0xad, 0x0d, 0x80, 0x84, 0xb0, 0x6c, 0xca, 0x4f, 0x3f, 0x97, 0x81, 0x59,
	0x59, 0x66, 0x27, 0xc7, 0x86, 0x01, 0x5b, 0x7e, 0xca, 0xd0, 0xff, 0xa1, 0x1b, 0x85, 0xf1, 0x88,
	0x97, 0xa5, 0xac, 0x52, 0x27, 0x0a, 0xe3, 0xe3, 0x30, 0x22, 0x47, 0x4c, 0xe0, 0xde, 0xa2, 0xc0,
	0x9b, 0x12, 0xf7, 0x16, 0x12, 0xd7, 0xb9, 0x6a, 0x5d, 0xc0, 0x95, 0xfb, 0xb3, 0x01, 0xe6, 0x51,
	0xb6, 0x40, 0xb7, 0x2b, 0xbb, 0xef, 0xf1, 0xc0, 0xa3, 0x6c, 0xa1, 0x2b, 0x7b, 0xab, 0xae, 0xec,
	0xbe, 0x0a, 0x3a, 0xa3, 0xe8, 0x6f, 0x24, 0x45, 0x5b, 0x60, 0x33, 0x61, 0x11, 0x39, 0xf7, 0xf2,
	0x13, 0xcd, 0x3a, 0xb0, 0xc2, 0xd1, 0x7d, 0xb0, 0x97, 0xf8, 0x93, 0xc2, 0x2a, 0x7b, 0x32, 0x2f,
	0xaa, 0xbf, 0x57, 0xd6, 0xff, 0x03, 0xe8, 0x05, 0xa5, 0x6d, 0xa8, 0x65, 0xac, 0x17, 0xcb, 0xd0,
	0x3c, 0x05, 0x57, 0x22, 0xab, 0xca, 0x31, 0xea, 0xca, 0xf9, 0xc9, 0x80, 0xe6, 0xa7, 0x34, 0xf6,
	0x09, 0x72, 0x2b, 0xc4, 0xad, 0xf0, 0xcc, 0x02, 0xd0, 0xa9, 0x7b, 0xbb, 0x4e, 0xdd, 0x5a, 0x19,
	0x76, 0x86, 0xbc, 0x97, 0x4a, 0x60, 0x1a, 0x25, 0x8d, 0x25, 0x94, 0xbc, 0x03, 0xd7, 0x84, 0x04,
	0x12, 0x2f, 0x3e, 0x25, 0xfc, 0xfc, 0x1b, 0x35, 0x5e, 0xc4, 0xc1, 0xc6, 0x1c, 0x1d, 0x06, 0x57,
	0x23, 0x10, 0x5f, 0xf1, 0x00, 0x89, 0xf3, 0x1e, 0xfb, 0x13, 0x9a, 0x90, 0xe0, 0xbc, 0x99, 0x41,
	0x81, 0xc3, 0xc0, 0xfd, 0xbb, 0x01, 0xad, 0xcf, 0xb2, 0x74, 0x96, 0xa5, 0xe8, 0x6e, 0x85, 0x32,
	0xa1, 0x89, 0x1c, 0xd1, 0x39, 0x73, 0xc0, 0xa6, 0x49, 0x10, 0xc6, 0xde, 0x54, 0x7a, 0x9e, 0x1a,
	0x0e, 0x7e, 0x54, 0x04, 0x6d, 0x40, 0x2b, 0x97, 0x8f, 0x9e, 0x49, 0x57, 0x97, 0x84, 0xd1, 0x01,
	0xf4, 0x7d, 0x1a, 0xa7, 0x09, 0x9d, 0x2e, 0xbb, 0x04, 0x57, 0x64, 0xcc, 0x95, 0xee, 0xc0, 0x0a,
	0x91, 0xd6, 0x45, 0xa7, 0xeb, 0x97, 0x06, 0x00, 0x26, 0x69, 0x98, 0x10, 0xce, 0x17, 0xda, 0xa8,
	0x6c, 0xfc, 0x3a, 0x8f, 0x2f, 0xd1, 0xab, 0x6d, 0x3e, 0x79, 0xd5, 0xbd, 0xab, 0x5d, 0x18, 0x97,
	0xee, 0xe2, 0x22, 0x39, 0xb8, 0x3f, 0x34, 0xa0, 0x73, 0xac, 0x34, 0x84, 0x1e, 0x54, 0x36, 0x81,
	0x84, 0x4f, 0x2a, 0x50, 0x37, 0xca, 0xe7, 0x72, 0xa5, 0x35, 0x1b, 0x6b, 0x5c, 0x62, 0x63, 0xc6,
	0x32, 0x1b, 0xbb, 0x70, 0x89, 0x7f, 0x9a, 0xd0, 0x1e, 0xca, 0x1e, 0xe6, 0x3c, 0x27, 0x57, 0x98,
	0x4e, 0xf2, 0x76, 0xfd, 0x54, 0xae, 0x57, 0x22, 0xeb, 0x07, 0x53, 0x2f, 0x8a, 0x59, 0x2d, 0xca,
	0x77, 0xe5, 0x91, 0xed, 0xe4, 0x92, 0x3f, 0xaf, 0x37, 0x6b, 0xe7, 0xd0, 0x30, 0xb8, 0x6a, 0x87,
	0xf2, 0xfa, 0x02, 0x1c, 0xfc, 0xd6, 0x28, 0x8f, 0xf2, 0x43, 0xe8, 0x6a, 0x0e, 0xa7, 0xf7, 0x32,
	0x67, 0xac, 0x50, 0x0f, 0x44, 0x1f, 0xc1, 0x6a, 0xde, 0xcb, 0x06, 0x45, 0x2f, 0x2a, 0x17, 0x7e,
	0xbd, 0x58, 0x78, 0xd9, 0xa6, 0xe2, 0xbe, 0x57, 0xeb, 0x5b, 0x2b, 0x16, 0x62, 0x5e, 0x62, 0x21,
	0xd6, 0x12, 0x0b, 0xf9, 0xc7, 0x80, 0xe6, 0xd3, 0x19, 0x89, 0x83, 0xf3, 0x4c, 0x57, 0x00, 0x97,
	0x9b, 0x6e, 0x1e, 0xf6, 0x0a, 0xb5, 0xfd, 0x5a, 0x96, 0x76, 0x07, 0xfa, 0x6c, 0x46, 0xe2, 0x74,
	0x44, 0x85, 0x55, 0x9d, 0x57, 0xe0, 0x6b, 0x22, 0x20, 0xb7, 0xb2, 0x61, 0xf0, 0x06, 0x4e, 0xde,
	0xe0, 0xdb, 0x37, 0x50, 0xbe, 0xa5, 0x17, 0x59, 0x9d, 0x7e, 0x73, 0x09, 0xfd, 0xbf, 0x1a, 0xe2,
	0x67, 0x2b, 0xa5, 0xc7, 0x0b, 0x74, 0x8f, 0x37, 0xa4, 0xbc, 0x35, 0xd2, 0x1b, 0x06, 0xd5, 0x2e,
	0x61, 0x89, 0xa1, 0x5b, 0xd0, 0x8c, 0xb2, 0x05, 0x51, 0x3d, 0x90, 0x2d, 0x1b, 0x06, 0x9c, 0xbf,
	0x45, 0x77, 0xa0, 0x15, 0xf3, 0x3b, 0x30, 0x57, 0x45, 0x77, 0xaf, 0x53, 0xdc, 0x8a, 0x58, 0x02,
	0xe8, 0x1e, 0xd8, 0x39, 0xdf, 0xbc, 0xff, 0xe1, 0x31, 0x50, 0xde, 0x16, 0x58, 0x41, 0x68, 0x07,
	0xba, 0x49, 0xe1, 0xa3, 0xbc, 0x13, 0x32, 0x95, 0x2a, 0x4a, 0x7b, 0xc5, 0x7a, 0x08, 0x7a, 0x17,
	0x80, 0x1b, 0x8e, 0xb8, 0x33, 0x99, 0xd3, 0x12, 0x1f, 0x5c, 0xab, 0x58, 0x19, 0xd6, 0x02, 0xd0,
	0x5b, 0xd0, 0x51, 0x7f, 0x48, 0xcc, 0xb1, 0x45, 0x74, 0x4f, 0x37, 0x0b, 0x5c, 0xc2, 0x7c, 0x57,
	0x5c, 0x07, 0x01, 0x73, 0xda, 0xe5, 0xae, 0x84, 0xec, 0xb0, 0x04, 0xdc, 0x13, 0x00, 0x41, 0xa4,
	0x68, 0xc8, 0xb9, 0x95, 0x57, 0xb8, 0xec, 0xd7, 0xfe, 0x18, 0x0a, 0x3a, 0xdf, 0x83, 0x9e, 0xde,
	0x71, 0x4b, 0x56, 0xd5, 0x1d, 0xc6, 0xeb, 0x82, 0x2b, 0x01, 0xe3, 0x96, 0xf8, 0xe1, 0xde, 0xff,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x41, 0xdb, 0x64, 0x7e, 0x7c, 0x0f, 0x00, 0x00,
}
