// Code generated by protoc-gen-go.
// source: snapshot.proto
// DO NOT EDIT!

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	snapshot.proto

It has these top-level messages:
	Snapshot
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Snapshot represents a snapshot of the blockchain, including the state
// tree and issuance memory.
type Snapshot struct {
	// Nodes contains every node within the state tree, including interior nodes.
	// The nodes are ordered according to a pre-order traversal.
	Nodes []*Snapshot_StateTreeNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	// Issuances contains the record of recent issuances for ensuring uniqueness
	// of issuances.
	Issuances []*Snapshot_Issuance `protobuf:"bytes,2,rep,name=issuances" json:"issuances,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Snapshot) GetNodes() []*Snapshot_StateTreeNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Snapshot) GetIssuances() []*Snapshot_Issuance {
	if m != nil {
		return m.Issuances
	}
	return nil
}

type Snapshot_Issuance struct {
	Hash     []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ExpiryMs uint64 `protobuf:"varint,2,opt,name=expiry_ms,json=expiryMs" json:"expiry_ms,omitempty"`
}

func (m *Snapshot_Issuance) Reset()                    { *m = Snapshot_Issuance{} }
func (m *Snapshot_Issuance) String() string            { return proto.CompactTextString(m) }
func (*Snapshot_Issuance) ProtoMessage()               {}
func (*Snapshot_Issuance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Snapshot_StateTreeNode struct {
	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Snapshot_StateTreeNode) Reset()                    { *m = Snapshot_StateTreeNode{} }
func (m *Snapshot_StateTreeNode) String() string            { return proto.CompactTextString(m) }
func (*Snapshot_StateTreeNode) ProtoMessage()               {}
func (*Snapshot_StateTreeNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func init() {
	proto.RegisterType((*Snapshot)(nil), "chain.core.txdb.internal.storage.Snapshot")
	proto.RegisterType((*Snapshot_Issuance)(nil), "chain.core.txdb.internal.storage.Snapshot.Issuance")
	proto.RegisterType((*Snapshot_StateTreeNode)(nil), "chain.core.txdb.internal.storage.Snapshot.StateTreeNode")
}

func init() { proto.RegisterFile("snapshot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0x4b, 0x2c,
	0x28, 0xce, 0xc8, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x48, 0xce, 0x48, 0xcc,
	0xcc, 0xd3, 0x4b, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0xa9, 0x48, 0x49, 0xd2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0x55, 0x5a, 0xc8, 0xc4,
	0xc5, 0x11, 0x0c, 0xd5, 0x24, 0xe4, 0xc7, 0xc5, 0x9a, 0x97, 0x9f, 0x92, 0x5a, 0x2c, 0xc1, 0xa8,
	0xc0, 0xac, 0xc1, 0x6d, 0x64, 0xa1, 0x47, 0x48, 0xbb, 0x1e, 0x4c, 0xab, 0x5e, 0x70, 0x49, 0x62,
	0x49, 0x6a, 0x48, 0x51, 0x6a, 0xaa, 0x1f, 0xd0, 0x80, 0x20, 0x88, 0x31, 0x42, 0x81, 0x5c, 0x9c,
	0x99, 0xc5, 0xc5, 0xa5, 0x89, 0x79, 0xc9, 0x40, 0x33, 0x99, 0xc0, 0x66, 0x1a, 0x93, 0x60, 0xa6,
	0x27, 0x54, 0x6f, 0x10, 0xc2, 0x14, 0x29, 0x6b, 0x2e, 0x0e, 0x98, 0xb0, 0x90, 0x10, 0x17, 0x4b,
	0x46, 0x62, 0x71, 0x06, 0xd0, 0xb5, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x90, 0x34, 0x17, 0x67,
	0x6a, 0x45, 0x41, 0x66, 0x51, 0x65, 0x7c, 0x2e, 0xc8, 0x4a, 0x46, 0x0d, 0x96, 0x20, 0x0e, 0x88,
	0x80, 0x6f, 0xb1, 0x94, 0x29, 0x17, 0x2f, 0x8a, 0x3b, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b,
	0xa1, 0x06, 0x80, 0x98, 0x70, 0x33, 0x99, 0x10, 0x66, 0x3a, 0x71, 0x46, 0xb1, 0x43, 0xdd, 0x96,
	0xc4, 0x06, 0x0e, 0x57, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x20, 0xad, 0x97, 0x69,
	0x01, 0x00, 0x00,
}
