#!/bin/sh

go install chain/cmd/migratedb
go install chain/cmd/corectl
go install chain/cmd/cored

dropdb core 2>/dev/null
createdb core
dropdb cb_core 2>/dev/null
createdb cb_core
dropdb pd_1_core 2>/dev/null
createdb pd_1_core
dropdb pd_2_core 2>/dev/null
createdb pd_2_core
dropdb pd_3_core 2>/dev/null
createdb pd_3_core

migratedb postgres:///core?sslmode=disable
migratedb postgres:///cb_core?sslmode=disable
migratedb postgres:///pd_1_core?sslmode=disable
migratedb postgres:///pd_2_core?sslmode=disable
migratedb postgres:///pd_3_core?sslmode=disable

# Configure generator

blockchain_id=`corectl config-generator | cut -d ' ' -f3`

# Activate generator

DATABASE_URL=postgres:///core?sslmode=disable cored &
generator_pid=$!

# Configure other cores

DATABASE_URL=postgres:///cb_core?sslmode=disable corectl config $blockchain_id http://localhost:1999
DATABASE_URL=postgres:///pd_1_core?sslmode=disable corectl config $blockchain_id http://localhost:1999
DATABASE_URL=postgres:///pd_2_core?sslmode=disable corectl config $blockchain_id http://localhost:1999
DATABASE_URL=postgres:///pd_3_core?sslmode=disable corectl config $blockchain_id http://localhost:1999

# Kill generator

kill $generator_pid
echo "DONE"
