// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package localdbtest is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestItem
*/
package localdbtest

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type TestItem struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *TestItem) Reset()         { *m = TestItem{} }
func (m *TestItem) String() string { return proto.CompactTextString(m) }
func (*TestItem) ProtoMessage()    {}

func init() {
}
