// Package static provides a handler for serving static assets from an in-memory
// map.
package static

import (
	"net/http"
	"strings"
	"time"
)

// use start time as a conservative bound for last-modified
var lastMod = time.Now()

type Handler struct {
	Assets map[string]string
	Index  string
}

func (h Handler) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	output, ok := h.Assets[r.URL.Path]
	if !ok && r.URL.Path == "" && h.Index != "" {
		output = h.Assets[h.Index]
	} else if !ok {
		http.NotFound(rw, r)
		return
	}

	// Some autogenerated documentation uses frames, e.g. Javadoc
	rw.Header().Set("X-Frame-Options", "SAMEORIGIN")

	http.ServeContent(rw, r, r.URL.Path, lastMod, strings.NewReader(output))
}
