DROP INDEX activity_accounts_account_id_idx;
DROP INDEX activity_accounts_activity_id_account_id_idx;
DROP INDEX activity_manager_node_id_idx;
DROP INDEX activity_manager_node_id_txid_idx;
DROP INDEX issuance_activity_assets_asset_id_idx;
DROP INDEX issuance_activity_assets_issuance_activity_id_asset_id_idx;
DROP INDEX issuance_activity_issuer_node_id_idx;
DROP INDEX issuance_activity_issuer_node_id_txid_idx;

DROP TABLE
activity,
activity_accounts,
issuance_activity,
issuance_activity_assets;
