// Code generated by protoc-gen-go.
// source: options.proto
// DO NOT EDIT!

/*
Package configpb is a generated protocol buffer package.

It is generated from these files:
	options.proto

It has these top-level messages:
	ValueTuple
	ValueSet
*/
package configpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueTuple struct {
	// values is an ordered list of the values in the tuple
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ValueTuple) Reset()                    { *m = ValueTuple{} }
func (m *ValueTuple) String() string            { return proto.CompactTextString(m) }
func (*ValueTuple) ProtoMessage()               {}
func (*ValueTuple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ValueTuple) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ValueSet struct {
	// tuples is an unordered list of the tuples in the set
	Tuples []*ValueTuple `protobuf:"bytes,1,rep,name=tuples" json:"tuples,omitempty"`
}

func (m *ValueSet) Reset()                    { *m = ValueSet{} }
func (m *ValueSet) String() string            { return proto.CompactTextString(m) }
func (*ValueSet) ProtoMessage()               {}
func (*ValueSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ValueSet) GetTuples() []*ValueTuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

func init() {
	proto.RegisterType((*ValueTuple)(nil), "configpb.ValueTuple")
	proto.RegisterType((*ValueSet)(nil), "configpb.ValueSet")
}

func init() { proto.RegisterFile("options.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0x2f, 0x48, 0x52, 0x52, 0xe1, 0xe2, 0x0a, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x29, 0x2d, 0xc8,
	0x49, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x03, 0xf1, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83,
	0xa0, 0x3c, 0x25, 0x0b, 0x2e, 0x0e, 0xb0, 0xaa, 0xe0, 0xd4, 0x12, 0x21, 0x1d, 0x2e, 0xb6, 0x12,
	0x90, 0x62, 0x88, 0x1a, 0x6e, 0x23, 0x11, 0x3d, 0x98, 0x61, 0x7a, 0x08, 0x93, 0x82, 0xa0, 0x6a,
	0x92, 0xd8, 0xc0, 0x16, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x49, 0xa7, 0x51, 0x9b, 0x81,
	0x00, 0x00, 0x00,
}
