#!/bin/bash

set -eo pipefail

: ${GOPATH:?must be set}

echo "Installing RocksDB"

echo $CHAIN
ls $CHAIN
ROCKSDB="$CHAIN"/vendor/github.com/facebook/rocksdb

cd $ROCKSDB
make static_lib
rm -f ROCKSDB/librocksdb.a