#!/bin/bash

set -e

# Pin to a specific nightly until we can get off nightly entirely
RUST_VERSION="nightly-2017-04-16"

curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}

~/.cargo/bin/cargo install rustfmt
~/.cargo/bin/cargo install clippy
~/.cargo/bin/cargo install cargo-audit
