#!/bin/bash

set -eo pipefail

# Install GCC 4.8 
wget -O /etc/yum.repos.d/devtools-2.repo https://people.centos.org/tru/devtools-2/devtools-2.repo
yum -y install devtoolset-2-binutils devtoolset-2-gcc devtoolset-2-gcc-c++
source /opt/rh/devtoolset-2/enable

# Installing RocksDB and Snappy
cd /usr/local/lib
wget -q https://s3.amazonaws.com/chain-ci/librocksdb.a
wget -q https://s3.amazonaws.com/chain-ci/libsnappy.a