// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package program

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")

	procGetModuleFileNameW = modkernel32.NewProc("GetModuleFileNameW")
)

func GetModuleFileName(hmodule uint32, buf *uint16, buflen uint32) (n uint32, err error) {
	r0, _, e1 := syscall.Syscall(procGetModuleFileNameW.Addr(), 3, uintptr(hmodule), uintptr(unsafe.Pointer(buf)), uintptr(buflen))
	n = uint32(r0)
	if n == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}
